sudo: required
services:
    - docker

before_install:
    - docker build -t sumanthkv/docker_react -f Dockerfile.dev .

script:
    - docker run sumanthkv/docker_react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-921338979412"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY   


        